require_relative ('models/customer')
require_relative ('models/film')
require_relative ('models/ticket')

require ('pry')

Ticket.delete_all()
Film.delete_all()
Customer.delete_all()

customer1 = Customer.new({ 'name' => 'Samwise Gamgee', 'funds' => 100 })
customer1.save()
customer2 = Customer.new({ 'name' => 'Frodo Baggins', 'funds' => 1500 })
customer2.save()
customer3 = Customer.new({ 'name' => 'Bilbo Baggins', 'funds' => 125500 })
customer3.save()
customer4 = Customer.new({ 'name' => 'Sackville Baggins', 'funds' => 0 })
customer4.save()
customer5 = Customer.new({ 'name' => 'Gandalf the Grey', 'funds' => 150 })
customer5.save()

film1 = Film.new({ 'title' => 'Lord of The Rings', 'price' => 6})
film1.save()
film2 = Film.new({ 'title' => 'Two Towers', 'price' => 6})
film2.save()
film3 = Film.new({ 'title' => 'Return of The King', 'price' => 6})
film3.save()
film4 = Film.new({ 'title' => 'The Hobbit', 'price' => 15})
film4.save()
film5 = Film.new({ 'title' => 'The Silmarillion', 'price' => 20})
film5.save()

ticket1 = Ticket.new ({ 'customer_id' => customer1.id, 'film_id' => film1.id })
ticket1.save()
ticket2 = Ticket.new ({ 'customer_id' => customer2.id, 'film_id' => film2.id })
ticket2.save()
ticket3 = Ticket.new ({ 'customer_id' => customer3.id, 'film_id' => film3.id })
ticket3.save()
ticket4 = Ticket.new ({ 'customer_id' => customer4.id, 'film_id' => film4.id })
ticket4.save()
ticket5 = Ticket.new ({ 'customer_id' => customer5.id, 'film_id' => film4.id })
ticket5.save()

binding.pry
nil